function add_transformer(modelName, cfg)

blk = [modelName '/Transformer'];

add_block('powerlib/Elements/Three-Phase Transformer (Two Windings)', blk,...
    'Position',[150 150 300 260]);

Pn = cfg.tf.rating_kVA * 1e3;     % VA
fn = cfg.f_nom;                  % Hz

V1 = cfg.tf.V_HV * 1e3;          % HV line-line
V2 = cfg.tf.V_LV * 1e3;          % LV line-line

R_pu = cfg.tf.Z_pu / sqrt(1 + (cfg.tf.XR^2));
X_pu = cfg.tf.XR * R_pu;
L_pu = X_pu / (2*pi*fn);            % pu inductance

set_param(blk,...
    'UNITS','pu',...
    'NominalPower',sprintf('[%g %g]',Pn,fn),...
    'Winding1',sprintf('[%g %g %g]',V1,R_pu,L_pu),...
    'Winding2',sprintf('[%g %g %g]',V2,R_pu,L_pu),...
    'Winding1Connection','Delta (D11)',...
    'Winding2Connection','Yg',...
    'Rm','500',...
    'Lm','500',...
    'Measurements','None');
end
