function add_line_PI(modelName, from, to, span_m, condType, cond, pos)

blk = [modelName '/Line_' from '_' to];

add_block('powerlib/Elements/Three-Phase PI Section Line', blk,...
    'Position',pos);

l_km = span_m/1000;
condType = ['ABC' extractAfter(seg.Conductor,'ABC')];
c = cond.(condType);

set_param(blk,...
 'Frequency','50',...
 'Length',num2str(l_km),...
 'ResistancePerLength',mat2str(c.r),...
 'InductancePerLength',mat2str(c.l),...
 'CapacitancePerLength',mat2str(c.c));

end
